spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: MY_KEY
            client-secret: MY_KEY
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

# logging:
#  level:
#    org.springframework.security: DEBUG
