spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: MY_KEY
            client-secret: MY_KEY

#logging:
#  level:
#    org.springframework.security: DEBUG
